from Stack import StackNode, Stack

newstack = Stack()
newstack.push(111)
newstack.push(222)
print(newstack.top)
print(newstack.top.next)
print(newstack.top.next.next)
print(newstack.top.next.next.next)
newstack.push(333)
newstack.push(444)
print(newstack.top)
print(newstack.size)
newstack.pop()
print(newstack.top)
print(newstack.size)
print('~~~~~~~~~working here~~~~~~~~~')
print(newstack.pop())
print(newstack.top)
print(newstack.size)
print(newstack)