from Stack import StackNode, Stack

newstack = Stack()
newstack.push(55)
newstack.push(5511)
print(newstack.top)
print(newstack.top.next)
print(newstack.top.next.next)
print(newstack.top.next.next.next)
newstack.push(333)
print(newstack.top)
print(newstack.size)
newstack.pop()
print('~~~~~~~~~working here~~~~~~~~~')
print(newstack.top)
print(newstack.size)
